// Tamil Nadu 2026 Legislative Assembly Election — All 234 Constituency Winners
// Source: Election Commission of India (ECI) official results
// Results declared: 4–5 May 2026

const electionWinners2026 = [
  { constituencyNo: 1,   constituencyName: "Gummidipoondi",           districtName: "Tiruvallur",       candidateName: "S. Vijayakumar",               partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 2,   constituencyName: "Ponneri",                 districtName: "Tiruvallur",       candidateName: "Dr. M. S. Ravi",               partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 3,   constituencyName: "Tiruttani",               districtName: "Tiruvallur",       candidateName: "G. Hari",                      partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 4,   constituencyName: "Thiruvallur",             districtName: "Tiruvallur",       candidateName: "Dr. T. Arunkumar",             partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 5,   constituencyName: "Poonamallee",             districtName: "Tiruvallur",       candidateName: "R. Prakasam",                  partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 6,   constituencyName: "Avadi",                   districtName: "Tiruvallur",       candidateName: "R. Ramesh Kumar",              partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 7,   constituencyName: "Maduravoyal",             districtName: "Chennai",          candidateName: "Rhevanth Charan",              partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 8,   constituencyName: "Ambattur",                districtName: "Chennai",          candidateName: "G. Balamurugan",               partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 9,   constituencyName: "Madhavaram",              districtName: "Chennai",          candidateName: "M. L. Vijayprabhu",            partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 10,  constituencyName: "Thiruvottiyur",           districtName: "Chennai",          candidateName: "N. Senthil Kumar",             partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 11,  constituencyName: "Dr. Radhakrishnan Nagar", districtName: "Chennai",          candidateName: "N. Marie Wilson",              partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 12,  constituencyName: "Perambur",                districtName: "Chennai",          candidateName: "C. Joseph Vijay",              partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 13,  constituencyName: "Kolathur",                districtName: "Chennai",          candidateName: "V. S. Babu",                   partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 14,  constituencyName: "Villivakkam",             districtName: "Chennai",          candidateName: "Aadhav Arjuna",                partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 15,  constituencyName: "Thiru-Vi-Ka-Nagar",       districtName: "Chennai",          candidateName: "M. R. Pallavi",                partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 16,  constituencyName: "Egmore",                  districtName: "Chennai",          candidateName: "Rajmohan",                     partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 17,  constituencyName: "Royapuram",               districtName: "Chennai",          candidateName: "K. V. Vijay Damu",             partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 18,  constituencyName: "Harbour",                 districtName: "Chennai",          candidateName: "P. K. Sekar Babu",             partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 19,  constituencyName: "Chepauk-Thiruvallikeni",  districtName: "Chennai",          candidateName: "Udhayanidhi Stalin",           partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 20,  constituencyName: "Thousand Lights",         districtName: "Chennai",          candidateName: "J. C. D. Prabhakar",           partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 21,  constituencyName: "Anna Nagar",              districtName: "Chennai",          candidateName: "V. K. Ramkumar",               partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 22,  constituencyName: "Virugambakkam",           districtName: "Chennai",          candidateName: "R. Sabarinathan",              partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 23,  constituencyName: "Saidapet",                districtName: "Chennai",          candidateName: "M. Arul Prakasam",             partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 24,  constituencyName: "Thiyagarayanagar",        districtName: "Chennai",          candidateName: "N. Anand",                     partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 25,  constituencyName: "Mylapore",                districtName: "Chennai",          candidateName: "P. Venkataramanan",            partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 26,  constituencyName: "Velachery",               districtName: "Chennai",          candidateName: "R. Kumar",                     partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 27,  constituencyName: "Sholinganallur",          districtName: "Chennai",          candidateName: "ECR P. Saravanan",             partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 28,  constituencyName: "Alandur",                 districtName: "Chennai",          candidateName: "M. Harish",                    partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 29,  constituencyName: "Sriperumbudur",           districtName: "Kanchipuram",      candidateName: "K. Thennarasu",                partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 30,  constituencyName: "Pallavaram",              districtName: "Chengalpattu",     candidateName: "J. Kamatchi",                  partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 31,  constituencyName: "Tambaram",                districtName: "Chengalpattu",     candidateName: "D. Sarathkumar",               partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 32,  constituencyName: "Chengalpattu",            districtName: "Chengalpattu",     candidateName: "S. Thiyagarajan",              partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 33,  constituencyName: "Thiruporur",              districtName: "Chengalpattu",     candidateName: "B. Vijayaraj",                 partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 34,  constituencyName: "Cheyyur",                 districtName: "Chengalpattu",     candidateName: "E. Rajasekar",                 partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 35,  constituencyName: "Madurantakam",            districtName: "Chengalpattu",     candidateName: "K. Maragatham Kumaravel",      partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 36,  constituencyName: "Uthiramerur",             districtName: "Kanchipuram",      candidateName: "J. Munirathinam",              partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 37,  constituencyName: "Kancheepuram",            districtName: "Kanchipuram",      candidateName: "R. V. Ranjithkumar",           partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 38,  constituencyName: "Arakkonam",               districtName: "Ranipet",          candidateName: "V. Gandhiraj",                 partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 39,  constituencyName: "Sholinghur",              districtName: "Ranipet",          candidateName: "G. Kapil",                     partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 40,  constituencyName: "Katpadi",                 districtName: "Vellore",          candidateName: "Dr. M. Sudhakar",              partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 41,  constituencyName: "Ranipet",                 districtName: "Ranipet",          candidateName: "Thahira",                      partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 42,  constituencyName: "Arcot",                   districtName: "Ranipet",          candidateName: "S. M. Sukumar",                partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 43,  constituencyName: "Vellore",                 districtName: "Vellore",          candidateName: "M. M. Vinoth Kannan",          partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 44,  constituencyName: "Anaikattu",               districtName: "Vellore",          candidateName: "D. Velazhagan",                partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 45,  constituencyName: "Kilvaithinankuppam",      districtName: "Vellore",          candidateName: "E. Thenral Kumar",             partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 46,  constituencyName: "Gudiyattam",              districtName: "Vellore",          candidateName: "K. Sindu",                     partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 47,  constituencyName: "Vaniyambadi",             districtName: "Tirupattur",       candidateName: "Syed Farooq Basha SSB",        partyAffiliation: "Indian Union Muslim League" },
  { constituencyNo: 48,  constituencyName: "Ambur",                   districtName: "Tirupattur",       candidateName: "A. C. Vilwanathan",            partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 49,  constituencyName: "Jolarpet",                districtName: "Tirupattur",       candidateName: "K. C. Veeramani",              partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 50,  constituencyName: "Tirupattur",              districtName: "Tirupattur",       candidateName: "Dr. N. Thirupathi",            partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 51,  constituencyName: "Uthangarai",              districtName: "Krishnagiri",      candidateName: "N. Elaiyaraja",                partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 52,  constituencyName: "Bargur",                  districtName: "Krishnagiri",      candidateName: "E. C. Govindarasan",           partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 53,  constituencyName: "Krishnagiri",             districtName: "Krishnagiri",      candidateName: "P. Mukundhan",                 partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 54,  constituencyName: "Veppanahalli",            districtName: "Krishnagiri",      candidateName: "P. S. Srinivasan",             partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 55,  constituencyName: "Hosur",                   districtName: "Krishnagiri",      candidateName: "P. Balakrishna Reddy",         partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 56,  constituencyName: "Thalli",                  districtName: "Krishnagiri",      candidateName: "T. Ramachandran",              partyAffiliation: "Communist Party of India" },
  { constituencyNo: 57,  constituencyName: "Palacode",                districtName: "Dharmapuri",       candidateName: "K. P. Anbalagan",              partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 58,  constituencyName: "Pennagaram",              districtName: "Dharmapuri",       candidateName: "S. Gajendran",                 partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 59,  constituencyName: "Dharmapuri",              districtName: "Dharmapuri",       candidateName: "Sowmiya Anbumani",             partyAffiliation: "Pattali Makkal Katchi" },
  { constituencyNo: 60,  constituencyName: "Pappireddipatti",         districtName: "Dharmapuri",       candidateName: "Maragatham Vetrivel",          partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 61,  constituencyName: "Harur",                   districtName: "Dharmapuri",       candidateName: "V. Sampathkumar",              partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 62,  constituencyName: "Chengam",                 districtName: "Tiruvannamalai",   candidateName: "S. Velu",                      partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 63,  constituencyName: "Tiruvannamalai",          districtName: "Tiruvannamalai",   candidateName: "E. V. Velu",                   partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 64,  constituencyName: "Kilpennathur",            districtName: "Tiruvannamalai",   candidateName: "S. Ramachandran",              partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 65,  constituencyName: "Kalasapakkam",            districtName: "Tiruvannamalai",   candidateName: "S. S. Agri Krishnamurthy",     partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 66,  constituencyName: "Polur",                   districtName: "Tiruvannamalai",   candidateName: "R. Abishek",                   partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 67,  constituencyName: "Arani",                   districtName: "Tiruvannamalai",   candidateName: "L. Jayasudha",                 partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 68,  constituencyName: "Cheyyar",                 districtName: "Tiruvannamalai",   candidateName: "Mukkur N. Subramanian",        partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 69,  constituencyName: "Vandavasi",               districtName: "Tiruvannamalai",   candidateName: "S. Ambethkumar",               partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 70,  constituencyName: "Gingee",                  districtName: "Villupuram",       candidateName: "A. Ganesh Kumar",              partyAffiliation: "Pattali Makkal Katchi" },
  { constituencyNo: 71,  constituencyName: "Mailam",                  districtName: "Villupuram",       candidateName: "C. Ve. Shanmugam",             partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 72,  constituencyName: "Tindivanam",              districtName: "Villupuram",       candidateName: "Vanni Arasu",                  partyAffiliation: "Viduthalai Chiruthaigal Katchi" },
  { constituencyNo: 73,  constituencyName: "Vanur",                   districtName: "Villupuram",       candidateName: "D. Gowtham",                   partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 74,  constituencyName: "Villupuram",              districtName: "Villupuram",       candidateName: "R. Lakshmanan",                partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 75,  constituencyName: "Vikravandi",              districtName: "Villupuram",       candidateName: "C. Sivakumar",                 partyAffiliation: "Pattali Makkal Katchi" },
  { constituencyNo: 76,  constituencyName: "Tirukkoyilur",            districtName: "Villupuram",       candidateName: "S. Palanisamy",                partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 77,  constituencyName: "Ulundurpettai",           districtName: "Kallakurichi",     candidateName: "G. R. Vasanthavel",            partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 78,  constituencyName: "Rishivandiyam",           districtName: "Kallakurichi",     candidateName: "K. Karthikeyan",               partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 79,  constituencyName: "Sankarapuram",            districtName: "Kallakurichi",     candidateName: "R. Rakesh",                    partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 80,  constituencyName: "Kallakurichi",            districtName: "Kallakurichi",     candidateName: "C. Arul Vignesh",              partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 81,  constituencyName: "Gangavalli",              districtName: "Salem",            candidateName: "A. Nallathambi",               partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 82,  constituencyName: "Attur",                   districtName: "Salem",            candidateName: "A. P. Jayasankaran",           partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 83,  constituencyName: "Yercaud",                 districtName: "Salem",            candidateName: "P. Usharani",                  partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 84,  constituencyName: "Omalur",                  districtName: "Salem",            candidateName: "R. Mani",                      partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 85,  constituencyName: "Mettur",                  districtName: "Salem",            candidateName: "G. Venkatachalam",             partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 86,  constituencyName: "Edappadi",                districtName: "Salem",            candidateName: "Edappadi K. Palaniswami",      partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 87,  constituencyName: "Sankari",                 districtName: "Salem",            candidateName: "S. Vetrivel",                  partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 88,  constituencyName: "Salem West",              districtName: "Salem",            candidateName: "S. Lakshmanan",                partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 89,  constituencyName: "Salem North",             districtName: "Salem",            candidateName: "K. Sivakumar",                 partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 90,  constituencyName: "Salem South",             districtName: "Salem",            candidateName: "A. Vijay Tamilan Parthiban",   partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 91,  constituencyName: "Veerapandi",              districtName: "Salem",            candidateName: "M. S. Palanivel",              partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 92,  constituencyName: "Rasipuram",               districtName: "Namakkal",         candidateName: "D. Logesh Tamilselvan",        partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 93,  constituencyName: "Senthamangalam",          districtName: "Namakkal",         candidateName: "P. Chandrasekar",              partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 94,  constituencyName: "Namakkal",                districtName: "Namakkal",         candidateName: "C. S. Dilip",                  partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 95,  constituencyName: "Paramathi-Velur",         districtName: "Namakkal",         candidateName: "S. Sekar",                     partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 96,  constituencyName: "Tiruchengodu",            districtName: "Namakkal",         candidateName: "K. G. Arunraj",                partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 97,  constituencyName: "Kumarapalayam",           districtName: "Namakkal",         candidateName: "C. Vijayalakshmi",             partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 98,  constituencyName: "Erode East",              districtName: "Erode",            candidateName: "M. Vijay Balaji",              partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 99,  constituencyName: "Erode West",              districtName: "Erode",            candidateName: "K. K. Ananth Moghan",          partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 100, constituencyName: "Modakkurichi",            districtName: "Erode",            candidateName: "D. Shanmugan",                 partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 101, constituencyName: "Dharapuram",              districtName: "Tiruppur",         candidateName: "P. Sathyabama",                partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 102, constituencyName: "Kangayam",                districtName: "Tiruppur",         candidateName: "N. S. N. Nataraj",             partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 103, constituencyName: "Perundurai",              districtName: "Erode",            candidateName: "S. Jayakumar",                 partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 104, constituencyName: "Bhavani",                 districtName: "Erode",            candidateName: "K. C. Karuppanan",             partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 105, constituencyName: "Anthiyur",                districtName: "Erode",            candidateName: "P. Haribaskar",                partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 106, constituencyName: "Gobichettipalayam",       districtName: "Erode",            candidateName: "K. A. Sengottaiyan",           partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 107, constituencyName: "Bhavanisagar",            districtName: "Erode",            candidateName: "V. P. Tamilselvi",             partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 108, constituencyName: "Udhagamandalam",          districtName: "Nilgiris",         candidateName: "M. Bhojarajan",                partyAffiliation: "Bharatiya Janata Party" },
  { constituencyNo: 109, constituencyName: "Gudalur",                 districtName: "Nilgiris",         candidateName: "M. Dhravidamani",              partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 110, constituencyName: "Coonoor",                 districtName: "Nilgiris",         candidateName: "M. Raju",                      partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 111, constituencyName: "Mettupalayam",            districtName: "Coimbatore",       candidateName: "Sunilanand",                   partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 112, constituencyName: "Avanashi",                districtName: "Tiruppur",         candidateName: "S. Kamali",                    partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 113, constituencyName: "Tiruppur North",          districtName: "Tiruppur",         candidateName: "V. Sathyabama",                partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 114, constituencyName: "Tiruppur South",          districtName: "Tiruppur",         candidateName: "S. Balamurugan",               partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 115, constituencyName: "Palladam",                districtName: "Tiruppur",         candidateName: "K. Ramkumar",                  partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 116, constituencyName: "Sulur",                   districtName: "Coimbatore",       candidateName: "N. M. Sukumar",                partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 117, constituencyName: "Kavundampalayam",         districtName: "Coimbatore",       candidateName: "Kanimozhi Santhosh",           partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 118, constituencyName: "Coimbatore North",        districtName: "Coimbatore",       candidateName: "V. Sampathkumar",              partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 119, constituencyName: "Thondamuthur",            districtName: "Coimbatore",       candidateName: "S. P. Velumani",               partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 120, constituencyName: "Coimbatore South",        districtName: "Coimbatore",       candidateName: "V. Senthil Balaji",            partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 121, constituencyName: "Singanallur",             districtName: "Coimbatore",       candidateName: "K. S. Sri Giri Prasath",       partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 122, constituencyName: "Kinathukadavu",           districtName: "Coimbatore",       candidateName: "K. Vignesh",                   partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 123, constituencyName: "Pollachi",                districtName: "Coimbatore",       candidateName: "K. Nithyanandhan",             partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 124, constituencyName: "Valparai",                districtName: "Coimbatore",       candidateName: "A. Kutty (Sudhakar)",          partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 125, constituencyName: "Udumalaipettai",          districtName: "Tiruppur",         candidateName: "M. Jayakumar",                 partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 126, constituencyName: "Madathukulam",            districtName: "Tiruppur",         candidateName: "R. Jayaramakrishnan",          partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 127, constituencyName: "Palani",                  districtName: "Dindigul",         candidateName: "K. Ravi Manoharan",            partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 128, constituencyName: "Oddanchatram",            districtName: "Dindigul",         candidateName: "R. Sakkarapani",               partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 129, constituencyName: "Athoor",                  districtName: "Dindigul",         candidateName: "I. Periyasamy",                partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 130, constituencyName: "Nilakottai",              districtName: "Dindigul",         candidateName: "R. Ayyanar",                   partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 131, constituencyName: "Natham",                  districtName: "Dindigul",         candidateName: "Natham R. Viswanathan",        partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 132, constituencyName: "Dindigul",                districtName: "Dindigul",         candidateName: "I. P. Senthilkumar",           partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 133, constituencyName: "Vedasandur",              districtName: "Dindigul",         candidateName: "T. Saminathan",                partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 134, constituencyName: "Aravakurichi",            districtName: "Karur",            candidateName: "R. Elango",                    partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 135, constituencyName: "Karur",                   districtName: "Karur",            candidateName: "M. R. Vijayabhaskar",          partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 136, constituencyName: "Krishnarayapuram",        districtName: "Karur",            candidateName: "M. Sathya",                    partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 137, constituencyName: "Kulithalai",              districtName: "Karur",            candidateName: "Suriyanur A. Chandran",        partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 138, constituencyName: "Manapparai",              districtName: "Tiruchirappalli",  candidateName: "R. Kathiravan",                partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 139, constituencyName: "Srirangam",               districtName: "Tiruchirappalli",  candidateName: "Ramesh",                       partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 140, constituencyName: "Tiruchirappalli West",    districtName: "Tiruchirappalli",  candidateName: "K. N. Nehru",                  partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 141, constituencyName: "Tiruchirappalli East",    districtName: "Tiruchirappalli",  candidateName: "C. Joseph Vijay",              partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 142, constituencyName: "Thiruverumbur",           districtName: "Tiruchirappalli",  candidateName: "Navalpattu S. Viji",           partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 143, constituencyName: "Lalgudi",                 districtName: "Tiruchirappalli",  candidateName: "Leema Rose Martin",            partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 144, constituencyName: "Manachanallur",           districtName: "Tiruchirappalli",  candidateName: "S. Kathiravan",                partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 145, constituencyName: "Musiri",                  districtName: "Tiruchirappalli",  candidateName: "M. Vignesh",                   partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 146, constituencyName: "Thuraiyur",               districtName: "Tiruchirappalli",  candidateName: "M. Ravisankar",                partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 147, constituencyName: "Perambalur",              districtName: "Perambalur",       candidateName: "K. Sivakumar",                 partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 148, constituencyName: "Kunnam",                  districtName: "Perambalur",       candidateName: "S. S. Sivasankar",             partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 149, constituencyName: "Ariyalur",                districtName: "Ariyalur",         candidateName: "S. Rajendran",                 partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 150, constituencyName: "Jayankondam",             districtName: "Ariyalur",         candidateName: "G. Vaithilingam",              partyAffiliation: "Pattali Makkal Katchi" },
  { constituencyNo: 151, constituencyName: "Tittakudi",               districtName: "Cuddalore",        candidateName: "C. V. Ganesan",                partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 152, constituencyName: "Vriddhachalam",           districtName: "Cuddalore",        candidateName: "Premalatha Vijayakant",        partyAffiliation: "Desiya Murpokku Dravida Kazhagam" },
  { constituencyNo: 153, constituencyName: "Neyveli",                 districtName: "Cuddalore",        candidateName: "R. Rajendran",                 partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 154, constituencyName: "Panruti",                 districtName: "Cuddalore",        candidateName: "K. Mohan",                     partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 155, constituencyName: "Cuddalore",               districtName: "Cuddalore",        candidateName: "B. Rajkumar",                  partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 156, constituencyName: "Kurinjipadi",             districtName: "Cuddalore",        candidateName: "M. R. K. Panneerselvam",       partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 157, constituencyName: "Bhuvanagiri",             districtName: "Cuddalore",        candidateName: "A. Arunmozhithevan",           partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 158, constituencyName: "Chidambaram",             districtName: "Cuddalore",        candidateName: "M. Thamimun Ansari",           partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 159, constituencyName: "Kattumannarkoil",         districtName: "Cuddalore",        candidateName: "L. E. Jothimani",              partyAffiliation: "Viduthalai Chiruthaigal Katchi" },
  { constituencyNo: 160, constituencyName: "Sirkazhi",                districtName: "Mayiladuthurai",   candidateName: "R. Senthilselvan",             partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 161, constituencyName: "Mayiladuthurai",          districtName: "Mayiladuthurai",   candidateName: "Y. N. Jamal Mohamed Younoos",  partyAffiliation: "Indian National Congress" },
  { constituencyNo: 162, constituencyName: "Poompuhar",               districtName: "Mayiladuthurai",   candidateName: "Nivedha M. Murugan",           partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 163, constituencyName: "Nagapattinam",            districtName: "Nagapattinam",     candidateName: "M. H. Jawahirullah",           partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 164, constituencyName: "Kilvelur",                districtName: "Nagapattinam",     candidateName: "T. Latha",                     partyAffiliation: "Communist Party of India (Marxist)" },
  { constituencyNo: 165, constituencyName: "Vedaranyam",              districtName: "Nagapattinam",     candidateName: "O. S. Manian",                 partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 166, constituencyName: "Thiruthuraipoondi",       districtName: "Tiruvarur",        candidateName: "K. Marimuthu",                 partyAffiliation: "Communist Party of India" },
  { constituencyNo: 167, constituencyName: "Mannargudi",              districtName: "Tiruvarur",        candidateName: "S. Kamaraj",                   partyAffiliation: "Amma Makkal Munnettra Kazagam" },
  { constituencyNo: 168, constituencyName: "Thiruvarur",              districtName: "Tiruvarur",        candidateName: "K. Poondi Kalaivanan",         partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 169, constituencyName: "Nannilam",                districtName: "Tiruvarur",        candidateName: "R. Kamaraj",                   partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 170, constituencyName: "Thiruvidaimarudur",       districtName: "Thanjavur",        candidateName: "Govi. Chezhiaan",              partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 171, constituencyName: "Kumbakonam",              districtName: "Thanjavur",        candidateName: "Vinoth",                       partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 172, constituencyName: "Papanasam",               districtName: "Thanjavur",        candidateName: "A. M. Shahjahan",              partyAffiliation: "Indian Union Muslim League" },
  { constituencyNo: 173, constituencyName: "Thiruvaiyaru",            districtName: "Thanjavur",        candidateName: "Durai. Chandrasekaran",        partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 174, constituencyName: "Thanjavur",               districtName: "Thanjavur",        candidateName: "R. Vijay Saravanan",           partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 175, constituencyName: "Orathanadu",              districtName: "Thanjavur",        candidateName: "R. Vaithilingam",              partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 176, constituencyName: "Pattukkottai",            districtName: "Thanjavur",        candidateName: "K. Annadurai",                 partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 177, constituencyName: "Peravurani",              districtName: "Thanjavur",        candidateName: "N. Ashokkumar",                partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 178, constituencyName: "Gandarvakottai",          districtName: "Pudukkottai",      candidateName: "N. Subramanian",               partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 179, constituencyName: "Viralimalai",             districtName: "Pudukkottai",      candidateName: "C. Vijayabhaskar",             partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 180, constituencyName: "Pudukkottai",             districtName: "Pudukkottai",      candidateName: "V. Muthuraja",                 partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 181, constituencyName: "Thirumayam",              districtName: "Pudukkottai",      candidateName: "S. Regupathy",                 partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 182, constituencyName: "Alangudi",                districtName: "Pudukkottai",      candidateName: "Siva V. Meyyanathan",          partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 183, constituencyName: "Aranthangi",              districtName: "Pudukkottai",      candidateName: "J. Mohamed Farvas",            partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 184, constituencyName: "Karaikudi",               districtName: "Sivaganga",        candidateName: "Dr. T. K. Prabhu",             partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 185, constituencyName: "Tiruppattur",             districtName: "Sivaganga",        candidateName: "R. Seenivasa Sethupathy",      partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 186, constituencyName: "Sivaganga",               districtName: "Sivaganga",        candidateName: "A. Kulanthai Rani",            partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 187, constituencyName: "Manamadurai",             districtName: "Sivaganga",        candidateName: "D. Elangovan",                 partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 188, constituencyName: "Melur",                   districtName: "Madurai",          candidateName: "P. Viswanathan",               partyAffiliation: "Indian National Congress" },
  { constituencyNo: 189, constituencyName: "Madurai East",            districtName: "Madurai",          candidateName: "S. Karthikeyan",               partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 190, constituencyName: "Sholavandan",             districtName: "Madurai",          candidateName: "M. V. Karuppaiah",             partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 191, constituencyName: "Madurai North",           districtName: "Madurai",          candidateName: "A. Kallanai",                  partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 192, constituencyName: "Madurai South",           districtName: "Madurai",          candidateName: "M. M. Gopison",                partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 193, constituencyName: "Madurai Central",         districtName: "Madurai",          candidateName: "Madhar Badhurudeen",           partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 194, constituencyName: "Madurai West",            districtName: "Madurai",          candidateName: "S. R. Thangapandi",            partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 195, constituencyName: "Thiruparankundram",       districtName: "Madurai",          candidateName: "R. Nirmal Kumar",              partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 196, constituencyName: "Thirumangalam",           districtName: "Madurai",          candidateName: "M. Manimaran",                 partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 197, constituencyName: "Usilampatti",             districtName: "Madurai",          candidateName: "M. Vijay",                     partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 198, constituencyName: "Andipatti",               districtName: "Theni",            candidateName: "A. Maharajan",                 partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 199, constituencyName: "Periyakulam",             districtName: "Theni",            candidateName: "G. Sabari Iyngaran",           partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 200, constituencyName: "Bodinayakanur",           districtName: "Theni",            candidateName: "O. Panneerselvam",             partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 201, constituencyName: "Cumbum",                  districtName: "Theni",            candidateName: "P. L. A. Jeganath Mishra",     partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 202, constituencyName: "Rajapalayam",             districtName: "Virudhunagar",     candidateName: "K. Jegadeshwari",              partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 203, constituencyName: "Srivilliputhur",          districtName: "Virudhunagar",     candidateName: "A. Karthik",                   partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 204, constituencyName: "Sattur",                  districtName: "Virudhunagar",     candidateName: "A. Kadarkarairaj",             partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 205, constituencyName: "Sivakasi",                districtName: "Virudhunagar",     candidateName: "S. Keerthana",                 partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 206, constituencyName: "Virudhunagar",            districtName: "Virudhunagar",     candidateName: "P. Selvam",                    partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 207, constituencyName: "Aruppukkottai",           districtName: "Virudhunagar",     candidateName: "K. K. S. S. R. Ramachandran", partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 208, constituencyName: "Tiruchuli",               districtName: "Virudhunagar",     candidateName: "Thangam Thennarasu",           partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 209, constituencyName: "Paramakudi",              districtName: "Ramanathapuram",   candidateName: "K. K. Advocate Kathiravan",    partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 210, constituencyName: "Tiruvadanai",             districtName: "Ramanathapuram",   candidateName: "Rajeev",                       partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 211, constituencyName: "Ramanathapuram",          districtName: "Ramanathapuram",   candidateName: "Katharbatcha Muthuramalingam", partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 212, constituencyName: "Mudukulathur",            districtName: "Ramanathapuram",   candidateName: "R. S. Rajakannappan",          partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 213, constituencyName: "Vilathikulam",            districtName: "Thoothukudi",      candidateName: "G. V. Markandayan",            partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 214, constituencyName: "Thoothukudi",             districtName: "Thoothukudi",      candidateName: "Srinath",                      partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 215, constituencyName: "Tiruchendur",             districtName: "Thoothukudi",      candidateName: "Anitha R. Radhakrishnan",      partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 216, constituencyName: "Srivaikuntam",            districtName: "Thoothukudi",      candidateName: "G. Saravanan",                 partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 217, constituencyName: "Ottapidaram",             districtName: "Thoothukudi",      candidateName: "P. Mathanraja",                partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 218, constituencyName: "Kovilpatti",              districtName: "Thoothukudi",      candidateName: "K. Karunanithi",               partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 219, constituencyName: "Sankarankovil",           districtName: "Tenkasi",          candidateName: "Dr. Dhilipan Jaishankar",      partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 220, constituencyName: "Vasudevanallur",          districtName: "Tenkasi",          candidateName: "E. Raja",                      partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 221, constituencyName: "Kadayanallur",            districtName: "Tenkasi",          candidateName: "T. M. Rajendran",              partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 222, constituencyName: "Tenkasi",                 districtName: "Tenkasi",          candidateName: "Dr. Kalai Kathiravan",         partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 223, constituencyName: "Alangulam",               districtName: "Tenkasi",          candidateName: "Paul Manoj Pandian",           partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 224, constituencyName: "Tirunelveli",             districtName: "Tirunelveli",      candidateName: "R. S. Murugan",                partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 225, constituencyName: "Ambasamudram",            districtName: "Tirunelveli",      candidateName: "Dr. Esakki Subaya",            partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 226, constituencyName: "Palayamkottai",           districtName: "Tirunelveli",      candidateName: "M. Abdul Wahab",               partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 227, constituencyName: "Nanguneri",               districtName: "Tirunelveli",      candidateName: "Reddiarpatti V. Narayanan",    partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 228, constituencyName: "Radhapuram",              districtName: "Tirunelveli",      candidateName: "Dr. Sathish Christopher",      partyAffiliation: "Tamilaga Vettri Kazhagam" },
  { constituencyNo: 229, constituencyName: "Kanniyakumari",           districtName: "Kanyakumari",      candidateName: "N. Thalavai Sundaram",         partyAffiliation: "All India Anna Dravida Munnetra Kazhagam" },
  { constituencyNo: 230, constituencyName: "Nagercoil",               districtName: "Kanyakumari",      candidateName: "Austin",                       partyAffiliation: "Dravida Munnetra Kazhagam" },
  { constituencyNo: 231, constituencyName: "Colachal",                districtName: "Kanyakumari",      candidateName: "Tharahai Cuthbert",            partyAffiliation: "Indian National Congress" },
  { constituencyNo: 232, constituencyName: "Padmanabhapuram",         districtName: "Kanyakumari",      candidateName: "R. Chellaswamy",               partyAffiliation: "Communist Party of India (Marxist)" },
  { constituencyNo: 233, constituencyName: "Vilavancode",             districtName: "Kanyakumari",      candidateName: "T. T. Praveen",                partyAffiliation: "Indian National Congress" },
  { constituencyNo: 234, constituencyName: "Killiyoor",               districtName: "Kanyakumari",      candidateName: "S. Rajesh Kumar",              partyAffiliation: "Indian National Congress" },
];

// ── PARTY-WISE TALLY ─────────────────────────────────────────────────────────
// Tamilaga Vettri Kazhagam (TVK)                    : 108
// Dravida Munnetra Kazhagam (DMK)                   :  59
// All India Anna Dravida Munnetra Kazhagam (AIADMK) :  47
// Indian National Congress (INC)                    :   5
// Pattali Makkal Katchi (PMK)                       :   4
// Indian Union Muslim League (IUML)                 :   2
// Communist Party of India (CPI)                    :   2
// Viduthalai Chiruthaigal Katchi (VCK)              :   2
// Communist Party of India (Marxist) (CPI-M)        :   2
// Bharatiya Janata Party (BJP)                      :   1
// Desiya Murpokku Dravida Kazhagam (DMDK)           :   1
// Amma Makkal Munnettra Kazagam (AMMK)              :   1
// TOTAL                                             : 234
